--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Bumbumkill/ShulkerBox
build-by-default: true
branches:
- master
projects:
  ShulkerBox:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: true
...
